 #!/bin/bash

# The script takes the zipped output from computeMatrix (averagePlot.sh) and 
# generates average profile across the regions - plotProfile.
# The png with the profile and the actual values are saved to a folder
# named averageProfiles.


for d in */ ; do
    echo "$d"
    
    cd $d
    
    #make a directory, where average profiles will be stored - this 
	# should be easier to upload to R
	folder="averageProfiles"
	mkdir $folder

	# go through all the .gz file generated by averagePlot.sh
	for i in *.gz
 	do 
 		# id= everything before "."
 		id="$( cut -d '.' -f 1 <<< "$i" )"
 		echo $id
 	
 		# define output names
 		pngOutput="${folder}/${id}.png"
 		profileOutput="${folder}/avgProfile_${id}.tab"
 	
 		plotProfile -m $i -o $pngOutput --outFileNameData $profileOutput
 	
	done
    
    cd ..
done


echo "  "
echo "Done!"